# Job con múltiples completions en paralelo
apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  # Número total de ejecuciones exitosas requeridas
  completions: 5
  # Cuántas pueden ejecutarse en paralelo
  parallelism: 2
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ['sh', '-c', 'echo "Processing item..." && sleep $(shuf -i 2-5 -n 1) && echo "Done!"']
      restartPolicy: Never
  backoffLimit: 4
