# Service ClusterIP - Solo accesible dentro del cluster
# Este es el tipo por defecto
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80        # Puerto del servicio
    targetPort: 80  # Puerto del container

---
# Deployment para probar el service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-for-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
