# Service NodePort - Expone en un puerto del nodo
# Rango de puertos: 30000-32767
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
  ports:
  - port: 80         # Puerto interno del servicio
    targetPort: 80   # Puerto del container
    nodePort: 30080  # Puerto externo (opcional, K8s asigna si no lo especificas)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nodeport
  template:
    metadata:
      labels:
        app: nginx-nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
