# Namespace con recursos
apiVersion: v1
kind: Namespace
metadata:
  name: lab-demo
  labels:
    environment: demo
    team: platform

---
# Deployment en el namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Service en el namespace
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: lab-demo
spec:
  selector:
    app: nginx
  ports:
  - port: 80
