# StatefulSet con Headless Service
# Cada pod tiene: nombre estable, DNS, y storage persistente

# Headless Service (clusterIP: None)
# Permite acceder a pods individuales por DNS
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None  # Headless!
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"  # Nombre del headless service
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  
  # VolumeClaimTemplates - crear PVC por cada pod
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

# DNS de cada pod:
# web-0.nginx.default.svc.cluster.local
# web-1.nginx.default.svc.cluster.local
# web-2.nginx.default.svc.cluster.local
