# ServiceAccount para pods
# Los pods usan ServiceAccounts para autenticarse con la API de Kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: default

---
# Pod usando el ServiceAccount
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sa
spec:
  serviceAccountName: app-service-account
  containers:
  - name: app
    image: nginx:alpine
